/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Customer {
    totalOrders: bigint;
    name: string;
    email?: string;
    address: string;
    phone: string;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface OrderedItem {
    sareeId: bigint;
    quantity: bigint;
}
export interface Order {
    id: bigint;
    customerName: string;
    status: OrderStatus;
    customerPhone: string;
    orderDate: Time;
    items: Array<OrderedItem>;
    totalPrice: bigint;
}
export interface Saree {
    id: bigint;
    fabricType: FabricType;
    name: string;
    color: string;
    description: string;
    stock: bigint;
    image: ExternalBlob;
    price: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum FabricType {
    Kanjivaram = "Kanjivaram",
    Banarasi = "Banarasi",
    Mysore = "Mysore"
}
export enum OrderStatus {
    Delivered = "Delivered",
    Confirmed = "Confirmed",
    Shipped = "Shipped",
    Pending = "Pending"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addCustomer(name: string, phone: string, email: string | null, address: string): Promise<void>;
    addSaree(name: string, description: string, fabricType: FabricType, color: string, price: bigint, stock: bigint, image: ExternalBlob): Promise<bigint>;
    deleteSaree(id: bigint): Promise<void>;
    getAllCustomers(): Promise<Array<Customer>>;
    getAllOrders(): Promise<Array<Order>>;
    getAllSarees(): Promise<Array<Saree>>;
    getCustomer(phone: string): Promise<Customer>;
    getOrder(id: bigint): Promise<Order>;
    getSaree(id: bigint): Promise<Saree>;
    getSareesByPrice(): Promise<Array<Saree>>;
    placeOrder(customerName: string, customerPhone: string, items: Array<OrderedItem>): Promise<bigint>;
    updateCustomer(phone: string, name: string, email: string | null, address: string): Promise<void>;
    updateOrderStatus(id: bigint, status: OrderStatus): Promise<void>;
    updateSaree(id: bigint, name: string, description: string, fabricType: FabricType, color: string, price: bigint, stock: bigint, image: ExternalBlob): Promise<void>;
}
import type { Customer as _Customer, ExternalBlob as _ExternalBlob, FabricType as _FabricType, Order as _Order, OrderStatus as _OrderStatus, OrderedItem as _OrderedItem, Saree as _Saree, Time as _Time, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addCustomer(arg0: string, arg1: string, arg2: string | null, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async addSaree(arg0: string, arg1: string, arg2: FabricType, arg3: string, arg4: bigint, arg5: bigint, arg6: ExternalBlob): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSaree(arg0, arg1, to_candid_FabricType_n9(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, await to_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSaree(arg0, arg1, to_candid_FabricType_n9(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, await to_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async deleteSaree(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSaree(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSaree(arg0);
            return result;
        }
    }
    async getAllCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomers();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomers();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSarees(): Promise<Array<Saree>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSarees();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSarees();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: string): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_Customer_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_Customer_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: bigint): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_Order_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_Order_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSaree(arg0: bigint): Promise<Saree> {
        if (this.processError) {
            try {
                const result = await this.actor.getSaree(arg0);
                return from_candid_Saree_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSaree(arg0);
            return from_candid_Saree_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSareesByPrice(): Promise<Array<Saree>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSareesByPrice();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSareesByPrice();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeOrder(arg0: string, arg1: string, arg2: Array<OrderedItem>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, arg1, arg2);
            return result;
        }
    }
    async updateCustomer(arg0: string, arg1: string, arg2: string | null, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n27(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n27(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSaree(arg0: bigint, arg1: string, arg2: string, arg3: FabricType, arg4: string, arg5: bigint, arg6: bigint, arg7: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSaree(arg0, arg1, arg2, to_candid_FabricType_n9(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, await to_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSaree(arg0, arg1, arg2, to_candid_FabricType_n9(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, await to_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
}
function from_candid_Customer_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Customer): Customer {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FabricType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FabricType): FabricType {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
async function from_candid_Saree_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Saree): Promise<Saree> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalOrders: bigint;
    name: string;
    email: [] | [string];
    address: string;
    phone: string;
}): {
    totalOrders: bigint;
    name: string;
    email?: string;
    address: string;
    phone: string;
} {
    return {
        totalOrders: value.totalOrders,
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.email)),
        address: value.address,
        phone: value.phone
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    status: _OrderStatus;
    customerPhone: string;
    orderDate: _Time;
    items: Array<_OrderedItem>;
    totalPrice: bigint;
}): {
    id: bigint;
    customerName: string;
    status: OrderStatus;
    customerPhone: string;
    orderDate: Time;
    items: Array<OrderedItem>;
    totalPrice: bigint;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_OrderStatus_n19(_uploadFile, _downloadFile, value.status),
        customerPhone: value.customerPhone,
        orderDate: value.orderDate,
        items: value.items,
        totalPrice: value.totalPrice
    };
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    fabricType: _FabricType;
    name: string;
    color: string;
    description: string;
    stock: bigint;
    image: _ExternalBlob;
    price: bigint;
}): Promise<{
    id: bigint;
    fabricType: FabricType;
    name: string;
    color: string;
    description: string;
    stock: bigint;
    image: ExternalBlob;
    price: bigint;
}> {
    return {
        id: value.id,
        fabricType: from_candid_FabricType_n24(_uploadFile, _downloadFile, value.fabricType),
        name: value.name,
        color: value.color,
        description: value.description,
        stock: value.stock,
        image: await from_candid_ExternalBlob_n26(_uploadFile, _downloadFile, value.image),
        price: value.price
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Delivered: null;
} | {
    Confirmed: null;
} | {
    Shipped: null;
} | {
    Pending: null;
}): OrderStatus {
    return "Delivered" in value ? OrderStatus.Delivered : "Confirmed" in value ? OrderStatus.Confirmed : "Shipped" in value ? OrderStatus.Shipped : "Pending" in value ? OrderStatus.Pending : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Kanjivaram: null;
} | {
    Banarasi: null;
} | {
    Mysore: null;
}): FabricType {
    return "Kanjivaram" in value ? FabricType.Kanjivaram : "Banarasi" in value ? FabricType.Banarasi : "Mysore" in value ? FabricType.Mysore : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Customer>): Array<Customer> {
    return value.map((x)=>from_candid_Customer_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n17(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Saree>): Promise<Array<Saree>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Saree_n22(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FabricType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FabricType): _FabricType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FabricType): {
    Kanjivaram: null;
} | {
    Banarasi: null;
} | {
    Mysore: null;
} {
    return value == FabricType.Kanjivaram ? {
        Kanjivaram: null
    } : value == FabricType.Banarasi ? {
        Banarasi: null
    } : value == FabricType.Mysore ? {
        Mysore: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    Delivered: null;
} | {
    Confirmed: null;
} | {
    Shipped: null;
} | {
    Pending: null;
} {
    return value == OrderStatus.Delivered ? {
        Delivered: null
    } : value == OrderStatus.Confirmed ? {
        Confirmed: null
    } : value == OrderStatus.Shipped ? {
        Shipped: null
    } : value == OrderStatus.Pending ? {
        Pending: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
