/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const FabricType = IDL.Variant({
  'Kanjivaram' : IDL.Null,
  'Banarasi' : IDL.Null,
  'Mysore' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Customer = IDL.Record({
  'totalOrders' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'Delivered' : IDL.Null,
  'Confirmed' : IDL.Null,
  'Shipped' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Time = IDL.Int;
export const OrderedItem = IDL.Record({
  'sareeId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'customerPhone' : IDL.Text,
  'orderDate' : Time,
  'items' : IDL.Vec(OrderedItem),
  'totalPrice' : IDL.Nat,
});
export const Saree = IDL.Record({
  'id' : IDL.Nat,
  'fabricType' : FabricType,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'image' : ExternalBlob,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'addSaree' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        FabricType,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        ExternalBlob,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteSaree' : IDL.Func([IDL.Nat], [], []),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllSarees' : IDL.Func([], [IDL.Vec(Saree)], ['query']),
  'getCustomer' : IDL.Func([IDL.Text], [Customer], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
  'getSaree' : IDL.Func([IDL.Nat], [Saree], ['query']),
  'getSareesByPrice' : IDL.Func([], [IDL.Vec(Saree)], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(OrderedItem)],
      [IDL.Nat],
      [],
    ),
  'updateCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updateSaree' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        FabricType,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        ExternalBlob,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const FabricType = IDL.Variant({
    'Kanjivaram' : IDL.Null,
    'Banarasi' : IDL.Null,
    'Mysore' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Customer = IDL.Record({
    'totalOrders' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'Delivered' : IDL.Null,
    'Confirmed' : IDL.Null,
    'Shipped' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Time = IDL.Int;
  const OrderedItem = IDL.Record({ 'sareeId' : IDL.Nat, 'quantity' : IDL.Nat });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'customerPhone' : IDL.Text,
    'orderDate' : Time,
    'items' : IDL.Vec(OrderedItem),
    'totalPrice' : IDL.Nat,
  });
  const Saree = IDL.Record({
    'id' : IDL.Nat,
    'fabricType' : FabricType,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'image' : ExternalBlob,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'addSaree' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          FabricType,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          ExternalBlob,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteSaree' : IDL.Func([IDL.Nat], [], []),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllSarees' : IDL.Func([], [IDL.Vec(Saree)], ['query']),
    'getCustomer' : IDL.Func([IDL.Text], [Customer], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
    'getSaree' : IDL.Func([IDL.Nat], [Saree], ['query']),
    'getSareesByPrice' : IDL.Func([], [IDL.Vec(Saree)], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(OrderedItem)],
        [IDL.Nat],
        [],
      ),
    'updateCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updateSaree' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          FabricType,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          ExternalBlob,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };