/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Customer {
  'totalOrders' : bigint,
  'name' : string,
  'email' : [] | [string],
  'address' : string,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export type FabricType = { 'Kanjivaram' : null } |
  { 'Banarasi' : null } |
  { 'Mysore' : null };
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : OrderStatus,
  'paymentStatus' : string,
  'customerPhone' : string,
  'orderDate' : Time,
  'items' : Array<OrderedItem>,
  'totalPrice' : bigint,
  'productDetails' : Array<ProductDetail>,
}
export type OrderStatus = { 'Delivered' : null } |
  { 'Confirmed' : null } |
  { 'Cancelled' : null } |
  { 'Shipped' : null } |
  { 'Pending' : null };
export interface OrderedItem { 'sareeId' : bigint, 'quantity' : bigint }
export interface ProductDetail {
  'fabricType' : FabricType,
  'name' : string,
  'color' : string,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export interface Saree {
  'id' : bigint,
  'fabricType' : FabricType,
  'name' : string,
  'color' : string,
  'description' : string,
  'stock' : bigint,
  'image' : ExternalBlob,
  'price' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomer' : ActorMethod<
    [string, string, [] | [string], string],
    undefined
  >,
  'addSaree' : ActorMethod<
    [string, string, FabricType, string, bigint, bigint, ExternalBlob],
    { 'StorageError' : string }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteSaree' : ActorMethod<[bigint], undefined>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllSarees' : ActorMethod<[], Array<Saree>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[string], Customer>,
  'getOrder' : ActorMethod<[bigint], Order>,
  'getSaree' : ActorMethod<[bigint], Saree>,
  'getSareesByPrice' : ActorMethod<[], Array<Saree>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<
    [string, string, Array<OrderedItem>, Array<ProductDetail>],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCustomer' : ActorMethod<
    [string, string, [] | [string], string],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updatePaymentStatus' : ActorMethod<[bigint, string], undefined>,
  'updateSaree' : ActorMethod<
    [bigint, string, string, FabricType, string, bigint, bigint, ExternalBlob],
    { 'StorageError' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];